name: Update Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily at 00:00

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 30 mins

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update sources
        run: |
          nix run .#legacyPackages.x86_64-linux.runInRepoRoot.update-version-manifest-v2

          if git diff --quiet sources/version_manifest_v2.json; then
            echo "Manifest unchanged. Skipping asset SHA updates."
          else
            echo "Manifest changed. Running SHA update scripts..."
            nix run .#legacyPackages.x86_64-linux.runInRepoRoot.update-asset-sha256-all
          fi

          nix run .#legacyPackages.x86_64-linux.runInRepoRoot.update-paper-servers
          nix run .#legacyPackages.x86_64-linux.runInRepoRoot.update-modloader-locks

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sources/
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update sources"
            git push
          fi
